name = "doodlydoo"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Christian Stewart"]
maintainers = ["Christian Stewart <christianstewart.v1.0@gmail.com>"]
maintainers-logins = ["weaslepalace"]

executables = ["doodlydoo"]
[[depends-on]]
aunit = "^23.0.0"
[[depends-on]]
asfml = "^2.5.3"
